### PR TITLE
Update newtab.html

### PR DESCRIPTION
**Pull request by davelacorneille**
On my chrome on ubuntu, can't have the dark mode with the "light option"

### CODE REVIEW

**Comment by gdh1995** [comment]
Sorry but your change is not what `newtab.html` should be.

1. It should follow browser's advice - light on light, and dark on dark.
2. And I think `light dark` is valid according to https://drafts.csswg.org/css-color-adjust/#color-scheme-prop .
3. On my Chrome 98 and Win 10, `[content=dark]` will make the page dark even when Chrome is in light mode

So it seems your Chrome's issue if i cann't send states of the system-level dark mode to webpages. Maybe there're tricks to fix it but I haven't found.

The simplest way to bypass this issue is to add a local HTML file and set `Target new tab URL` to `file:///path/to/your.html`

**Comment by davelacorneille** [comment]
Thank you for your help!

Unfortunately, when I'm using a local file as my target on my windows 10
system and ubuntu system, Vimium C is not working anymore (I think for
security reasons).  My workaround is to create a simple black website on a
free hosting and use it as a target.  But with this solution, Chrome
display a bright white page for one or two seconds before the black web
page and it's annoying! :)

Still thank you very much for your help and all your work for these
extensions.

**Comment by gdh1995** [comment]
As for the flashing white page, it's difficult to avoid it on Ctrl+T. But as said in https://github.com/gdh1995/vimium-c/issues/580#issuecomment-1072128304 :
> A simpler way is to avoid Ctrl+T / click the + button on tab bar, but always use keys of Vimium C to create tabs (after configure New tab URL on Vimium C Options). You may map a key like Alt+T to create new tab following https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#global-shortcuts

**Comment by davelacorneille** [comment]
It's working! :)

Thank you so much.

**Pull request closed without merging**
